-- Cairn independent persistence foundation
-- Apply this migration to the user's Supabase project before switching the
-- application database adapter. It intentionally preserves numeric IDs so the
-- existing MySQL data can be migrated without rewriting every relationship.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  name text,
  email text,
  login_method text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name varchar(80) not null,
  description varchar(220) not null default '',
  project_kind text not null default 'general' check (project_kind in ('general', 'primary_law')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, name)
);
create index if not exists projects_user_idx on public.projects(user_id);

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  name varchar(80) not null,
  root_url varchar(1024) not null,
  scope text not null,
  audience varchar(120) not null,
  tone varchar(120) not null,
  answer_mode text not null default 'extractive',
  ai_synthesis_enabled boolean not null default false,
  source_authority text not null default 'general',
  publisher varchar(180) not null default '',
  source_map_url varchar(1024),
  include_paths text not null,
  exclude_paths text not null,
  page_limit integer not null default 20,
  import_status text not null default 'idle',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists collections_user_idx on public.collections(user_id);
create index if not exists collections_project_idx on public.collections(project_id);

create table if not exists public.import_batches (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.collections(id) on delete cascade,
  status text not null default 'running',
  requested_count integer not null,
  processed_count integer not null default 0,
  unchanged_count integer not null default 0,
  failed_count integer not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists import_batches_collection_idx on public.import_batches(collection_id);

create table if not exists public.source_archives (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.collections(id) on delete cascade,
  source_url varchar(1024) not null,
  file_name varchar(255) not null,
  archive_sha256 varchar(64) not null,
  observed_etag varchar(128),
  observed_last_modified timestamptz,
  acquired_at timestamptz not null,
  record_count integer not null,
  source_file_storage_key varchar(1024),
  source_file_storage_url varchar(1024),
  source_file_sha256 varchar(64),
  source_file_bytes bigint,
  extract_storage_key varchar(1024) not null,
  extract_storage_url varchar(1024) not null,
  extract_sha256 varchar(64) not null,
  created_at timestamptz not null default now(),
  unique(collection_id, archive_sha256)
);
create index if not exists source_archives_collection_idx on public.source_archives(collection_id);

create table if not exists public.collection_pages (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.collections(id) on delete cascade,
  import_batch_id bigint references public.import_batches(id) on delete set null,
  canonical_url varchar(1024) not null,
  official_record_key varchar(255),
  official_text_sha256 varchar(64),
  official_citation_metadata jsonb,
  page_title text not null,
  headings jsonb not null,
  clean_text text,
  content_hash varchar(64) not null,
  source_status text not null default 'queued',
  import_error text,
  fetched_at timestamptz,
  imported_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(collection_id, canonical_url),
  unique(collection_id, official_record_key)
);
create index if not exists collection_pages_batch_idx on public.collection_pages(import_batch_id);

create table if not exists public.passages (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.collections(id) on delete cascade,
  page_id bigint not null references public.collection_pages(id) on delete cascade,
  position integer not null,
  heading_path text not null,
  anchor varchar(180) not null,
  text text not null,
  content_hash varchar(64) not null,
  created_at timestamptz not null default now()
);
create index if not exists passages_collection_idx on public.passages(collection_id);
create index if not exists passages_page_idx on public.passages(page_id);

create table if not exists public.page_snapshots (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.collection_pages(id) on delete cascade,
  import_batch_id bigint references public.import_batches(id) on delete set null,
  source_archive_id bigint references public.source_archives(id) on delete set null,
  version integer not null,
  page_title text not null,
  headings jsonb not null,
  official_citation_metadata jsonb,
  clean_text text not null,
  content_hash varchar(64) not null,
  fetched_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(page_id, version)
);
create index if not exists page_snapshots_page_idx on public.page_snapshots(page_id);
create index if not exists page_snapshots_batch_idx on public.page_snapshots(import_batch_id);
create index if not exists page_snapshots_archive_idx on public.page_snapshots(source_archive_id);

create table if not exists public.uploaded_documents (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  collection_id bigint not null references public.collections(id) on delete cascade,
  page_id bigint not null references public.collection_pages(id) on delete cascade,
  file_name varchar(255) not null,
  mime_type varchar(120) not null,
  byte_size bigint not null,
  storage_key varchar(1024) not null unique,
  storage_url varchar(1024) not null,
  status text not null default 'processing',
  import_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists uploaded_documents_user_idx on public.uploaded_documents(user_id);
create index if not exists uploaded_documents_collection_idx on public.uploaded_documents(collection_id);

-- Persistent conversations are independent of the model provider.
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  title varchar(180),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists conversations_user_idx on public.conversations(user_id);
create index if not exists conversations_project_idx on public.conversations(project_id);

create table if not exists public.conversation_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  citations jsonb,
  model_provider text,
  model_name text,
  created_at timestamptz not null default now()
);
create index if not exists conversation_messages_conversation_idx on public.conversation_messages(conversation_id, created_at);

-- Updated timestamps are maintained by Postgres rather than MySQL's onUpdateNow.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects for each row execute function public.set_updated_at();
drop trigger if exists collections_set_updated_at on public.collections;
create trigger collections_set_updated_at before update on public.collections for each row execute function public.set_updated_at();
drop trigger if exists collection_pages_set_updated_at on public.collection_pages;
create trigger collection_pages_set_updated_at before update on public.collection_pages for each row execute function public.set_updated_at();
drop trigger if exists uploaded_documents_set_updated_at on public.uploaded_documents;
create trigger uploaded_documents_set_updated_at before update on public.uploaded_documents for each row execute function public.set_updated_at();
drop trigger if exists conversations_set_updated_at on public.conversations;
create trigger conversations_set_updated_at before update on public.conversations for each row execute function public.set_updated_at();

-- Storage bucket. Files remain private; the server should issue signed URLs.
insert into storage.buckets (id, name, public)
values ('cairn-private', 'cairn-private', false)
on conflict (id) do update set public = false;

-- RLS is enabled now; policies are intentionally based on the Cairn users table.
alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.collections enable row level security;
alter table public.import_batches enable row level security;
alter table public.source_archives enable row level security;
alter table public.collection_pages enable row level security;
alter table public.passages enable row level security;
alter table public.page_snapshots enable row level security;
alter table public.uploaded_documents enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_messages enable row level security;

create or replace function public.current_cairn_user_id()
returns bigint language sql stable security definer set search_path = public
as $$ select id from public.users where auth_user_id = auth.uid() limit 1 $$;

-- Users can only see their own top-level records. The service role used by the
-- server bypasses RLS; browser clients should not receive the service key.
drop policy if exists users_self on public.users;
create policy users_self on public.users for all using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());
drop policy if exists projects_owner on public.projects;
create policy projects_owner on public.projects for all using (user_id = public.current_cairn_user_id()) with check (user_id = public.current_cairn_user_id());
drop policy if exists collections_owner on public.collections;
create policy collections_owner on public.collections for all using (user_id = public.current_cairn_user_id()) with check (user_id = public.current_cairn_user_id());
drop policy if exists conversations_owner on public.conversations;
create policy conversations_owner on public.conversations for all using (user_id = public.current_cairn_user_id()) with check (user_id = public.current_cairn_user_id());
drop policy if exists conversation_messages_owner on public.conversation_messages;
create policy conversation_messages_owner on public.conversation_messages for all using (conversation_id in (select id from public.conversations where user_id = public.current_cairn_user_id())) with check (conversation_id in (select id from public.conversations where user_id = public.current_cairn_user_id()));

-- Dependent knowledge records inherit ownership through their collection.
drop policy if exists import_batches_owner on public.import_batches;
create policy import_batches_owner on public.import_batches for all using (collection_id in (select id from public.collections where user_id = public.current_cairn_user_id())) with check (collection_id in (select id from public.collections where user_id = public.current_cairn_user_id()));
drop policy if exists source_archives_owner on public.source_archives;
create policy source_archives_owner on public.source_archives for all using (collection_id in (select id from public.collections where user_id = public.current_cairn_user_id())) with check (collection_id in (select id from public.collections where user_id = public.current_cairn_user_id()));
drop policy if exists collection_pages_owner on public.collection_pages;
create policy collection_pages_owner on public.collection_pages for all using (collection_id in (select id from public.collections where user_id = public.current_cairn_user_id())) with check (collection_id in (select id from public.collections where user_id = public.current_cairn_user_id()));
drop policy if exists passages_owner on public.passages;
create policy passages_owner on public.passages for all using (collection_id in (select id from public.collections where user_id = public.current_cairn_user_id())) with check (collection_id in (select id from public.collections where user_id = public.current_cairn_user_id()));
drop policy if exists page_snapshots_owner on public.page_snapshots;
create policy page_snapshots_owner on public.page_snapshots for all using (page_id in (select p.id from public.collection_pages p join public.collections c on c.id = p.collection_id where c.user_id = public.current_cairn_user_id())) with check (page_id in (select p.id from public.collection_pages p join public.collections c on c.id = p.collection_id where c.user_id = public.current_cairn_user_id()));
drop policy if exists uploaded_documents_owner on public.uploaded_documents;
create policy uploaded_documents_owner on public.uploaded_documents for all using (user_id = public.current_cairn_user_id()) with check (user_id = public.current_cairn_user_id());

-- Storage paths are expected to begin with the authenticated Cairn user's UUID.
drop policy if exists cairn_private_read on storage.objects;
create policy cairn_private_read on storage.objects for select to authenticated using (bucket_id = 'cairn-private' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists cairn_private_insert on storage.objects;
create policy cairn_private_insert on storage.objects for insert to authenticated with check (bucket_id = 'cairn-private' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists cairn_private_update on storage.objects;
create policy cairn_private_update on storage.objects for update to authenticated using (bucket_id = 'cairn-private' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'cairn-private' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists cairn_private_delete on storage.objects;
create policy cairn_private_delete on storage.objects for delete to authenticated using (bucket_id = 'cairn-private' and (storage.foldername(name))[1] = auth.uid()::text);
